import Vue from 'vue'
import { Button, Col, CheckboxGroup, Avatar, Checkbox, Switch, Select, DatePicker, TimePicker, Option, Form, FormItem, Input, Message, Container, Header, Main, Footer, Aside, Submenu, MenuItem, MenuItemGroup, Menu, Breadcrumb, Card, BreadcrumbItem } from 'element-ui'

Vue.use(Button)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Input)
Vue.use(Container)
Vue.use(Header)
Vue.use(Main)
Vue.use(Footer)
Vue.use(Aside)
Vue.use(Menu)
Vue.use(Submenu)
Vue.use(MenuItemGroup)
Vue.use(MenuItem)
Vue.use(Breadcrumb)
Vue.use(BreadcrumbItem)
Vue.use(Card)
Vue.use(Select)
Vue.use(Option)
Vue.use(DatePicker)
Vue.use(TimePicker)
Vue.use(Col)
Vue.use(Switch)
Vue.use(CheckboxGroup)
Vue.use(Checkbox)
Vue.use(Avatar)
Vue.prototype.$message = Message
